#Parameters:
#  NAME:
#    Type: String

Resources:  
  WebsiteBucket:
    Type: AWS::S3::Bucket    
    Properties:
      BucketName: !Sub "$udacity-3-bucket"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy    
    Properties:
      Bucket: !Ref 'udacity-3-bucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::udacity-3-bucket', !Ref 'udacity-3-bucket', /*]]